//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by Engel Alipio on 9/11/16.
//  Copyright © 2017 Agile Mobile Solutions. All rights reserved.
//

#import "MessagesViewController.h"
#import "StickerBrowserViewController.h"

@interface MessagesViewController ()
{
    StickerBrowserViewController *stickerBrowser;
}
-(void) logMethodName : (NSString *) anyMethod;
@end

@implementation MessagesViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    [self logMethodName:@"viewDidLoad"];
   
    if (! stickerBrowser){
        stickerBrowser = [[StickerBrowserViewController alloc] initWithStickerSize:MSStickerSizeRegular];
        stickerBrowser.view.frame = self.view.frame;
        [self addChildViewController:stickerBrowser];
        [stickerBrowser didMoveToParentViewController:self];
        [self.view addSubview:stickerBrowser.view];
    
    }
    [stickerBrowser changeBackGroundColor:[UIColor blackColor]];
    [stickerBrowser loadStickers];
    [stickerBrowser.stickerBrowserView reloadData];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
    [self logMethodName:@"didReceiveMemoryWarning"];

}

-(void) logMethodName : (NSString *) anyMethod{
    NSString *message = @"";
    @try {
        message = @"didBecomeActiveWithConversation invoked";
    } @catch (NSException *exception) {
        message = [exception description];
    } @finally {
        if ([message length] > 0){
            NSLog(@"%@",message);
        }
        message = @"";
    }

}

#pragma mark - Conversation Handling

-(void)didBecomeActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the inactive to active state.
    // This will happen when the extension is about to present UI.
    
    // Use this method to configure the extension and restore previously stored state.
        [self logMethodName:@"didBecomeActiveWithConversation"];
}

-(void)willResignActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
            [self logMethodName:@"willResignActiveWithConversation"];
}

-(void)didReceiveMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
    
    [self logMethodName:@"didReceiveMessage"];
}

-(void)didStartSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user taps the send button.
    [self logMethodName:@"didStartSendingMessage"];
}

-(void)didCancelSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
        [self logMethodName:@"didCancelSendingMessage"];
}

-(void)willTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called before the extension transitions to a new presentation style.
    
    // Use this method to prepare for the change in presentation style.
    
            [self logMethodName:@"willTransitionToPresentationStyle"];
}

-(void)didTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    // Called after the extension transitions to a new presentation style.
    
    // Use this method to finalize any behaviors associated with the change in presentation style.
    
    [self logMethodName:@"didTransitionToPresentationStyle"];
}

@end
